[build]
rustflags = ["-C", "link-arg=-Wl,-install_name,@rpath/libampere_core.dylib"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-install_name,@rpath/libampere_core.dylib"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-install_name,@rpath/libampere_core.dylib"]

